//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <algorithm>
#include <Rinternals.h>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
bool binarysearch(SEXP x,double v){
	bool res;
	switch(TYPEOF(x)){
		case INTSXP:{
			int *start=INTEGER(x);
			res = binary_search(start,start+LENGTH(x),v);
			break;
		}default:{
			double *start=REAL(x);
			res = binary_search(start,start+LENGTH(x),v);
			break;
		}
	}
	return res;
}

//[[Rcpp::export]]
int lowerbound(SEXP x,double v){
	bool res;
	switch(TYPEOF(x)){
		case INTSXP:{
			int *start=INTEGER(x);
			res = lower_bound(start,start+LENGTH(x),v)-start+1;
			break;
		}default:{
			double *start=REAL(x);
			res = lower_bound(start,start+LENGTH(x),v)-start+1;
			break;
		}
	}
	return res;
}

RcppExport SEXP Rfast_binarysearch(SEXP x,SEXP vSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< double >::type v(vSEXP);
    __result = wrap(binarysearch(x,v));
    return __result;
END_RCPP
}

RcppExport SEXP Rfast_lowerbound(SEXP x,SEXP vSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< double >::type v(vSEXP);
    __result = wrap(lowerbound(x,v));
    return __result;
END_RCPP
}
