//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rinternals.h>
#include <R.h>
#include "mn.h"

using namespace Rcpp;

//[[Rcpp::export]]
SEXP col_min_max(SEXP x,int nrow,int ncol){
  SEXP F;
  switch(TYPEOF(x)){
  	case REALSXP:{
  		F=PROTECT(Rf_allocMatrix(REALSXP,2,ncol));
  		double *xx=REAL(x),*end=xx+LENGTH(x),*f=REAL(F),min,max;
  		for(;xx!=end;xx+=nrow,f+=2){
  			min_max2(xx,xx+nrow,min,max);
			*f=min;
			f[1]=max;
	  	}
	  	break;
  	}
  	default:{
  		F=PROTECT(Rf_allocMatrix(INTSXP,2,ncol));
  		int *xx=INTEGER(x),*end=xx+LENGTH(x),*f=INTEGER(F),min,max;
		for(;xx!=end;xx+=nrow,f+=2){
		    min_max3(xx,xx+nrow,min,max);
		    *f=min;
		    f[1]=max;
		}
  	}
  }
  UNPROTECT(1);
  return F;
}


RcppExport SEXP Rfast_col_min_max(SEXP x,SEXP nrowSEXP,SEXP ncolSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< int >::type nrow(nrowSEXP);
    traits::input_parameter< int >::type ncol(ncolSEXP);
    __result = col_min_max(x,nrow,ncol);
    return __result;
END_RCPP
}
