//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include "mn.h"

using namespace Rcpp;

//[[Rcpp::export]]
arma::mat design_matrix(CharacterVector x,bool ones_c=true) {
  int i=0,n=x.size();
  std::vector< pair<string,int> > indices_copy_x(n);
  std::vector< pair<string,int> >::iterator a=indices_copy_x.begin();
  CharacterVector::iterator xx=x.begin();
  std::vector<string> leksi;
  arma::mat Final;
  for(;a!=indices_copy_x.end();++a,++i,++xx)
    *a=pair<string,int>(as<string>(*xx),i);
  sort(indices_copy_x.begin(), indices_copy_x.end(),my_compare1);
  leksi=as< vector<string> >(sort_unique(x));
  Final.resize(n,leksi.size());
  for(a=indices_copy_x.begin();a!=indices_copy_x.end();++a)
    Final.at((*a).second,lower_bound(leksi.begin(),leksi.end(),(*a).first)-leksi.begin())=1;
  if(ones_c)
    Final.col(0)=ones(n);
  else
  	Final.shed_col(leksi.size()-1); 
  return Final;
}

//the model.matrix form R but by collumn
RcppExport SEXP Rfast_design_matrix(SEXP xSEXP,SEXP onesSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< CharacterVector >::type x(xSEXP);
    traits::input_parameter< bool >::type ones(onesSEXP);
    __result = wrap(design_matrix(x,ones));
    return __result;
END_RCPP
}
