//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
std::vector<double> dg_vec(std::vector<double> x){
  std::vector<double>::iterator xx=x.begin();
  for(;xx!=x.end();++xx)
    *xx=digamma(*xx);
  return x;
}

RcppExport SEXP Rfast_dg_vec(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< std::vector<double> >::type x(xSEXP);
    __result = wrap(dg_vec(x));
    return __result;
END_RCPP
}
