//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <vector>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
colvec diri_nr_type2(colvec a1,colvec a2,colvec ma,int p,double tol){
  mat f2(p,p),slv;
  double sa;
  colvec f;
  while ( sum( abs( a2 - a1 ) ) > tol ) {
    a1 = a2;
    sa = sum(a1);
    f = ma - Digamma_v(a1,p) + digamma(sa);
    fill_m(f2.memptr(),f2.memptr()+p*p,trigamma(sa));
    f2.diag() = f2.diag() - Trigamma_v(a1,p);
    slv = solve(f2, f);
    a2 = a1 - slv.each_col();
  }
  return a2;
}

// part of the Compositional::diri.nr
colvec diri_nr_type2(colvec a1,colvec a2,colvec ma,int p,double tol);
RcppExport SEXP Rfast_diri_nr_type2(SEXP a1SEXP,SEXP a2SEXP,SEXP maSEXP,SEXP pSEXP,SEXP tolSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< colvec >::type a1(a1SEXP);
    traits::input_parameter< colvec >::type a2(a2SEXP);
    traits::input_parameter< colvec >::type ma(maSEXP);
    traits::input_parameter< int >::type p(pSEXP);
    traits::input_parameter< double >::type tol(tolSEXP);
    __result = wrap(diri_nr_type2(a1,a2,ma,p,tol));
    return __result;
END_RCPP
}
