//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
NumericVector diri_nr_type2(NumericVector a1, NumericVector a2, NumericVector ma,double tol){
  int n=a1.size(),i;
  NumericVector f,tr1(n),dg1(n),der;
  double sa,trsa,dgsa;
  while(sum(abs(a2-a1))>tol){
    a1=a2;
    sa=sum(a1);
    dgsa=digamma(sa);
    trsa=trigamma(sa);
    for(i=0;i<n;++i){
      tr1(i)=-trigamma(a1(i))+trsa;
      dg1(i)=ma(i)-digamma(a1(i))+dgsa;
    }
    a2=a1-dg1/tr1;
  }
  return a2;
}

// part of the Compositional::diri.nr
NumericVector diri_nr_type2(NumericVector a1, NumericVector a2, NumericVector ma,double tol);
RcppExport SEXP Rfast_diri_nr_type2(SEXP a1SEXP,SEXP a2SEXP,SEXP maSEXP,SEXP tolSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericVector >::type a1(a1SEXP);
    traits::input_parameter< NumericVector >::type a2(a2SEXP);
    traits::input_parameter< NumericVector >::type ma(maSEXP);
    traits::input_parameter< double >::type tol(tolSEXP);
    __result = wrap(diri_nr_type2(a1,a2,ma,tol));
    return __result;
END_RCPP
}
