// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include <algorithm>
#include <string>

using namespace Rcpp;
using namespace std;
using namespace arma;

// logistic
vec logistic_only(mat x, colvec y);
RcppExport SEXP Rfast_logistic_only(SEXP xSEXP,SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< colvec >::type y(ySEXP);
    __result = Rcpp::wrap(logistic_only(x,y));
    return __result;
END_RCPP
}

// poisson
vec poisson_only(mat x, colvec y);
RcppExport SEXP Rfast_poisson_only(SEXP xSEXP,SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< colvec >::type y(ySEXP);
    __result = Rcpp::wrap(poisson_only(x,y));
    return __result;
END_RCPP
}

// nth_element
double nth(vector<int> x, unsigned int elem);
RcppExport SEXP Rfast_nth(SEXP xSEXP,SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< vector<int> >::type x(xSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type y(ySEXP);
    __result = Rcpp::wrap(nth(x,y));
    return __result;
END_RCPP
}

// colMedians
vector<double> colmeds(mat x);
RcppExport SEXP Rfast_colmeds(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< mat >::type x(xSEXP);
    __result = Rcpp::wrap(colmeds(x));
    return __result;
END_RCPP
}
