//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include <algorithm>
#include <string>

using namespace Rcpp;
using namespace std;
using namespace arma;

// colMedians_p
vector<double> colmeds_p(mat x,int ncores);
RcppExport SEXP Rfast_colmeds_p(SEXP xSEXP,SEXP ncoresSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< mat >::type x(xSEXP);
    traits::input_parameter< int >::type ncores(ncoresSEXP);
    __result = wrap(colmeds_p(x,ncores));
    return __result;
END_RCPP
}

// sort_mat_p
mat sort_mat_p(mat x,int ncores);
RcppExport SEXP Rfast_sort_mat_p(SEXP xSEXP,SEXP ncoresSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< mat >::type x(xSEXP);
    traits::input_parameter< int >::type ncores(ncoresSEXP);
    __result = wrap(sort_mat_p(x,ncores));
    return __result;
END_RCPP
}

// colmax_p
vector<double> colmax_p(mat x,int ncores,bool value=false);
RcppExport SEXP Rfast_colmax_p(SEXP xSEXP,SEXP ncoresSEXP,SEXP valueSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< mat >::type x(xSEXP);
    traits::input_parameter< bool >::type value(valueSEXP);
    traits::input_parameter< int >::type ncores(ncoresSEXP);
    __result = wrap(colmax_p(x,ncores,value));
    return __result;
END_RCPP
}

// colmax_p
vector<double> colmin_p(mat x,int ncores,bool value=false);
RcppExport SEXP Rfast_colmin_p(SEXP xSEXP,SEXP ncoresSEXP,SEXP valueSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< mat >::type x(xSEXP);
    traits::input_parameter< int >::type ncores(ncoresSEXP);
    traits::input_parameter< bool >::type value(valueSEXP);
    __result = wrap(colmin_p(x,ncores,value));
    return __result;
END_RCPP
}
