//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<int> k_comb_n(int N, int K){
  vector<int> x;
  string bitmask(K, 1); // K leading 1's
  bitmask.resize(N, 0); // N-K trailing 0's
  int i;
  // print integers and permute bitmask
  do {
    for(i=0;i<N;++i) // [0..N-1] integers
      if(bitmask[i]) 
        x.push_back(i+1);
  }while(prev_permutation(bitmask.begin(),bitmask.end()));
  return x;
}

RcppExport SEXP Rfast_k_comb_n(SEXP nSEXP,SEXP kSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< int >::type n(nSEXP);
    traits::input_parameter< int >::type k(kSEXP);
    __result = wrap(k_comb_n(n,k));
    return __result;
END_RCPP
}
