//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>

using namespace Rcpp;
using namespace arma;

//[[Rcpp::export]]
mat kron(mat x,mat y){
  return kron(x,y);
}

RcppExport SEXP Rfast_kron(SEXP xSEXP,SEXP ySEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< mat >::type x(xSEXP);
    traits::input_parameter< mat >::type y(ySEXP);
    __result = wrap(kron(x,y));
    return __result;
END_RCPP
}
