//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<double> lower_triangle(NumericMatrix x){
  //NumericMatrix::iterator xx=x.begin();
  int ncl=x.ncol(),nrw=x.nrow(),i,j;
  vector<double> f;
  for(i=0;i<ncl;++i)
    for(j=i+1;j<nrw;++j)
      f.push_back(x(j,i));
  return f;
}

//[[Rcpp::export]]
LogicalMatrix lower_triangle_b(int nrw, int ncl){
  int i,j;
  LogicalMatrix f(nrw,ncl);
  for(i=0;i<ncl;++i)
    for(j=i+1;j<nrw;++j)
      f(j,i)=true;
  return f;
}

RcppExport SEXP Rfast_lower_triangle(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = wrap(lower_triangle(x));
    return __result;
END_RCPP
}

RcppExport SEXP Rfast_lower_triangle_b(SEXP nclSEXP, SEXP nrwSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< int >::type ncl(nclSEXP);
    traits::input_parameter< int >::type nrw(nrwSEXP);
    __result = wrap(lower_triangle_b(nrw,ncl));
    return __result;
END_RCPP
}
