//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <algorithm>

using namespace Rcpp;
using namespace std;


//[[Rcpp::export]]
IntegerVector Order(NumericVector x,const bool stable,const bool descend){
  IntegerVector ind=seq(1,x.size());
  switch(descend){
    case 1:{
      auto descend_func = [&](int i,int j){return x[i-1]>x[j-1];};
      stable ? stable_sort(ind.begin(),ind.end(),descend_func) : sort(ind.begin(),ind.end(),descend_func);
      break;
    }
    default:{
      auto func = [&](int i,int j){return x[i-1]<x[j-1];};
      stable ? stable_sort(ind.begin(),ind.end(),func) : sort(ind.begin(),ind.end(),func);
      break;
    }
  }
  return ind;
}

RcppExport SEXP Rfast_Order(SEXP xSEXP,SEXP stableSEXP,SEXP descendSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericVector >::type x(xSEXP);
    traits::input_parameter< const bool >::type stable(stableSEXP);
    traits::input_parameter< const bool >::type descend(descendSEXP);
    __result = wrap(Order(x,stable,descend));
    return __result;
END_RCPP
}
