//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include <algorithm>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<int> Order(vec x){
  int n=x.size(),i=0;
  vector< pair<double,int> > y(n);
  vector< pair<double,int> >::iterator a;
  vector<int>::iterator b;
  vector<int> f(n);
  NumericVector::iterator xx=x.begin();
  for(a=y.begin();a!=y.end();++a,++i,++xx)
    *a=pair<double,int>(*xx,i);
  sort(y.begin(),y.end(),my_compare_order);
  for(a=y.begin(),b=f.begin();a!=y.end();++a,++b)
    *b=a->second+1;
  return f;
}

RcppExport SEXP Rfast_Order(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< vec >::type x(xSEXP);
    __result = wrap(Order(x));
    return __result;
END_RCPP
}
