//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <algorithm>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
IntegerVector Order(NumericVector x,const bool stable){
  const int n=x.size();
  int i=0;
  pr *y=new pr[n];
  IntegerVector f(n);
  IntegerVector::iterator b=f.begin();
  NumericVector::iterator xx=x.begin();
  for(;i!=n;++i,++xx){
    y[i].first=*xx;
    y[i].second=i;
  }
  stable ? stable_sort(y,y+n,my_compare_order) : sort(y,y+n,my_compare_order);
  for(i=0;i!=n;++i,++b)
    *b=y[i].second+1;
  return f;
}

RcppExport SEXP Rfast_Order(SEXP xSEXP,SEXP stableSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericVector >::type x(xSEXP);
    traits::input_parameter< const bool >::type stable(stableSEXP);
    __result = wrap(Order(x,stable));
    return __result;
END_RCPP
}
