//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include "mn.h"

using namespace Rcpp;
using namespace std;
using namespace arma;

//[[Rcpp::export]]
mat regression(DataFrame x, colvec y){
  int size_F=x.length(),i;
  mat F(2,size_F);
  vector<int> pos=which_isFactor(x);
  DataFrame::iterator xx=x.begin();
  if(!pos.size()){
    for(i=0;i<size_F;++i,++xx){
      F.at(0,i)=regression_only_col(as<colvec>(*xx),y);
      F.at(1,i)=1;
    }
    return F;
  }
  int pos_f=0,ptf=0, n=x.nrows(),p;
  mat strtonum,tr_strtonum,b;
  double SSO=var(y)*(double)(n-1),SS1;
  colvec asses(y.n_rows);
  vec res;
  CharacterVector leksi;
  asses.fill(1);
  pos_f=pos[ptf]-1;
  for(i=0;i<size_F;++i,++xx){
    if(pos_f==i){
      leksi=*xx;
      strtonum=design_matrix(leksi,true);
      tr_strtonum=strtonum.t();
      b=inv(tr_strtonum*strtonum)*tr_strtonum*y; 
      res=y-strtonum*b; 
      SS1=var(res)*(n-1);
      p=strtonum.n_cols;
      F.at(0,i)=(SSO-SS1)*(n-p)/((p-1)*SS1);
      F.at(1,i)=p-1;
      ptf++;
      pos_f=pos[ptf]-1;
    }else{
      F.at(0,i)=regression_only_col(as<colvec>(*xx),y);
      F.at(1,i)=1;
    }
  }
  return F;
}

//regression
RcppExport SEXP Rfast_regression(SEXP xSEXP,SEXP ySEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< DataFrame >::type x(xSEXP);
    traits::input_parameter< colvec >::type y(ySEXP);
    __result = wrap(regression(x,y));
    return __result;
END_RCPP
}
