//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include "mn.h"

using namespace Rcpp;
using namespace std;
using namespace arma;

//[[Rcpp::export]]
mat regression(DataFrame x, colvec y){
  int pos_f=0,ptf=0, n=x.nrows(),p,size_F=x.length(),i=0;
  vec res;
  CharacterVector leksi;
  NumericVector x_i;
  colvec asses(y.n_rows);
  mat strtonum,tr_strtonum,b,F(2,size_F);
  double SSO=var(y)*(double)(n-1),SS1;
  vector<int> pos=which_isFactor(x);
  asses.fill(1);
  if(!pos.size()){
    for(;i<size_F;i++){
      x_i=x(i);
      F(0,i)=regression_only_col(as<colvec>(x_i),y);
      F(1,i)=1;
    }
    return F;
  }
  pos_f=pos[ptf]-1;
  for(;i<size_F;i++){
    if(pos_f==i){
      leksi=x(i);
      strtonum=design_matrix(leksi);
      tr_strtonum=strtonum.t();
      b=inv(tr_strtonum*strtonum)*tr_strtonum*y; 
      res=y-strtonum*b; 
      SS1=var(res)*(n-1);
      p=strtonum.n_cols;
      F(0,i)=(SSO-SS1)*(n-p)/((p-1)*SS1);
      F(1,i)=p-1;
      ptf++;
      pos_f=pos[ptf]-1;
    }else{
      x_i=x(i);
      F(0,i)=regression_only_col(as<colvec>(x_i),y);
      F(1,i)=1;
    }
  }
  return F;
}

//regression
RcppExport SEXP Rfast_regression(SEXP xSEXP,SEXP ySEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< DataFrame >::type x(xSEXP);
    traits::input_parameter< colvec >::type y(ySEXP);
    __result = wrap(regression(x,y));
    return __result;
END_RCPP
}
