//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>

using namespace Rcpp;
using namespace arma;

//[[Rcpp::export]]
mat rep_col(colvec x,const int n){
  return repmat(x,1,n);
}

RcppExport SEXP Rfast_rep_col(SEXP xSEXP,SEXP nSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< colvec >::type x(xSEXP);
    traits::input_parameter< const int >::type n(nSEXP);
    __result = wrap(rep_col(x,n));
    return __result;
END_RCPP
}
