//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<int> sort_int(vector<int> x){
  int sz=x.size(),aa;
  vector<int> f(sz,INT_MAX),ff,neg(sz,INT_MAX);
  vector<int>::iterator a=x.begin(),F=f.begin(),nn=neg.begin();
  vector<int>::reverse_iterator nr;
  for(;a!=x.end();++a){
    aa=*a;
    if(aa<0){
      if(-aa>sz){
        neg.resize(-aa+1,INT_MAX);
        nn=neg.begin();
      }
      *(nn-aa)=aa;
    }else{
      if(aa>sz){
        f.resize(aa+1,INT_MAX);
        F=f.begin();
      }
      *(F+aa)=aa;
    }
  }
  for(nr=neg.rbegin();nr!=neg.rend();++nr)
    if(*nr!=INT_MAX)
      ff.push_back(*nr);
  for(a=f.begin();a!=f.end();++a)
    if(*a!=INT_MAX)
      ff.push_back(*a);
  return ff;
}

RcppExport SEXP Rfast_sort_int(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< vector<int> >::type x(xSEXP);
    __result = wrap(sort_int(x));
    return __result;
END_RCPP
}
