//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<int> sort_uniq_int(vector<int> x){
  int aa,szn=1,szp=1,how_many_neg=0,how_many_pos=0;
  vector<int> f(1,INT_MAX),neg(1,INT_MAX),ff;
  vector<int>::iterator a=x.begin(),F=f.begin(),nn=neg.begin();
  vector<int>::reverse_iterator nr;
  for(;a!=x.end();++a){
    aa=*a;
    if(aa<0){
      if(-aa>=szn){
        neg.resize(-aa+1,INT_MAX);
        nn=neg.begin();
        szn=neg.size();
      }
      *(nn-aa)=aa;
      how_many_neg++;
    }else{
      if(aa>=szp){
        f.resize(aa+1,INT_MAX);
        F=f.begin();
        szp=f.size();
      }
      *(F+aa)=aa;
      how_many_pos++;
    }
  }
  if(how_many_neg)
    for(nr=neg.rbegin();nr!=neg.rend();++nr){
      if(*nr!=INT_MAX)
      	ff.push_back(*nr);
    }
  if(how_many_pos)
    for(a=f.begin();a!=f.end();++a){
      if(*a!=INT_MAX)
      	ff.push_back(*a);
    }
  return ff;
}

RcppExport SEXP Rfast_sort_uniq_int(SEXP xSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< vector<int> >::type x(xSEXP);
    __result = wrap(sort_uniq_int(x));
    return __result;
END_RCPP
}
