//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include "mn.h"

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
NumericMatrix tr_mat(NumericMatrix x){
  NumericMatrix::iterator xx=x.begin();
  for(;xx!=x.end();++xx)
    *xx=trigamma(*xx);
  return x;
}

RcppExport SEXP Rfast_tr_mat(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = wrap(tr_mat(x));
    return __result;
END_RCPP
}
