//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>
#include "mn.h"

using namespace Rcpp;
using namespace std;
using namespace arma;

//[[Rcpp::export]]
vector<double> tr_vec(vector<double> x){
  vector<double>::iterator xx=x.begin();
  for(;xx!=x.end();++xx)
    *xx=trigamma(*xx);
  return x;
}

RcppExport SEXP Rfast_tr_vec(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< vector<double> >::type x(xSEXP);
    __result = wrap(tr_vec(x));
    return __result;
END_RCPP
}
