//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<double> upper_triangle(NumericMatrix x){
  int ncl=x.ncol(),i,j;
  vector<double> f;
  for(i=1;i<ncl;++i)
    for(j=0;j<i;++j)
        f.push_back(x(j,i));
  return f;
}


//[[Rcpp::export]]
LogicalMatrix upper_triangle_b(int nrw, int ncl){
  int i,j;
  LogicalMatrix f(nrw,ncl);
  for(i=1;i<ncl;++i)
    for(j=0;j<i;++j)
      f(j,i)=true;
  return f;
}

vector<double> upper_triangle(NumericMatrix x);
RcppExport SEXP Rfast_upper_triangle(SEXP xSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< NumericMatrix >::type x(xSEXP);
    __result = wrap(upper_triangle(x));
    return __result;
END_RCPP
}

LogicalMatrix upper_triangle_b(int nrw, int ncl);
RcppExport SEXP Rfast_upper_triangle_b(SEXP nclSEXP, SEXP nrwSEXP){
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< int >::type ncl(nclSEXP);
    traits::input_parameter< int >::type nrw(nrwSEXP);
    __result = wrap(upper_triangle_b(nrw,ncl));
    return __result;
END_RCPP
}
