//Author: Manos Papadakis

// This file was generated by compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>
#include <vector>

using namespace Rcpp;
using namespace std;

//[[Rcpp::export]]
vector<int> which_isFactor(DataFrame x){
  vector<int> P;
  for(int i=0;i<x.length();++i)
    if(Rf_isFactor(x(i)))
      P.push_back(i+1);
   return P;
}

//find which collumns are factors
RcppExport SEXP Rfast_which_isFactor(SEXP xSEXP) {
BEGIN_RCPP
    RObject __result;
    RNGScope __rngScope;
    traits::input_parameter< DataFrame >::type x(xSEXP);
    __result = wrap(which_isFactor(x));
    return __result;
END_RCPP
}
