# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binary_search <- function(x, v, index=FALSE) {
	if(index){
  		return (.Call('Rfast_lowerbound',x,v))
	}
	.Call('Rfast_binarysearch',x,v)
}