# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_Mins_Maxs <- function(x) {
	dm <- dim(x)
  .Call('Rfast_col_min_max',x,dm[1],dm[2])
}