# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logistic_only <- function(x,y) {
  .Call('Rfast_logistic_only', PACKAGE = 'Rfast',x,y)
}

poisson_only <- function(x,y) {
  .Call('Rfast_poisson_only', PACKAGE = 'Rfast',x,y)
}

colMedians <- function(x) {
  .Call('Rfast_colmeds', PACKAGE = 'Rfast',x)
}

nth <- function(x,k) {
  .Call('Rfast_nth', PACKAGE = 'Rfast',x,k)
}