# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

design_matrix <- function(x) {
  .Call('Rfast_design_matrix', PACKAGE = 'Rfast',x)
}

logistic_only <- function(x,y) {
  .Call('Rfast_logistic_only', PACKAGE = 'Rfast',x,y)
}

poisson_only <- function(x,y) {
  .Call('Rfast_poisson_only', PACKAGE = 'Rfast',x,y)
}

regression <- function(x,y) {
  .Call('Rfast_regression', PACKAGE = 'Rfast',x,y)
}

colMedians <- function(x) {
  .Call('Rfast_colmeds', PACKAGE = 'Rfast',x)
}

nth <- function(x,k) {
  .Call('Rfast_nth', PACKAGE = 'Rfast',x,k)
}

sort_mat <- function(x) {
  .Call('Rfast_sort_mat', PACKAGE = 'Rfast',x)
}

colMaxs <- function(x,value=FALSE) {
  .Call('Rfast_colmax', PACKAGE = 'Rfast',x,value)
}

colMins <- function(x,value=FALSE) {
  .Call('Rfast_colmin', PACKAGE = 'Rfast',x,value)
}

which_isFactor <- function(x) {
  .Call('Rfast_which_isFactor', PACKAGE = 'Rfast',x)
}

med <- function(x) {
  .Call('Rfast_med', PACKAGE = 'Rfast',x)
}

hash.list <- function(key,x) {
  .Call('Rfast_Hash_list', PACKAGE = 'Rfast',key,x)
}

generate_key_1 <- function(x) {
  .Call('Rfast_generate_key_1', PACKAGE = 'Rfast',x)
}

generate_key_2 <- function(x) {
  .Call('Rfast_generate_key_2', PACKAGE = 'Rfast',x)
}

hash.find <- function(x,key) {
  .Call('Rfast_hash_find', PACKAGE = 'Rfast',x,key)
}

Match <- function(x,key) {
  .Call('Rfast_Match', PACKAGE = 'Rfast',x,key)
}

colmeans <- function(x) {
  .Call('Rfast_colmeans', PACKAGE = 'Rfast',x)
}

colsums <- function(x) {
  .Call('Rfast_colsums', PACKAGE = 'Rfast',x)
}

rowsums <- function(x) {
  .Call('Rfast_rowsums', PACKAGE = 'Rfast',x)
}

rowmeans <- function(x) {
  .Call('Rfast_rowmeans', PACKAGE = 'Rfast',x)
}

rowMaxs <- function(x) {
  .Call('Rfast_rowMaxs', PACKAGE = 'Rfast',x)
}

rowMins <- function(x) {
  .Call('Rfast_rowMins', PACKAGE = 'Rfast',x)
}

Rpois <- function(n,mu) {
  .Call('Rfast_Rpois', PACKAGE = 'Rfast',n,mu)
}

Runif <- function(n,mn,mx) {
  .Call('Rfast_Runif', PACKAGE = 'Rfast',n,mn,mx)
}

Rnorm <- function(n) {
  .Call('Rfast_Rnorm', PACKAGE = 'Rfast',n)
}

Rbeta <- function(n,a,b) {
  .Call('Rfast_Rbeta', PACKAGE = 'Rfast',n,a,b)
}

Rbinom <- function(n,nin,pp) {
  .Call('Rfast_Rbinom', PACKAGE = 'Rfast',n,nin,pp)
}