# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colMedians_parallel <- function(x,ncores) {
  .Call('Rfast_colmeds_p', PACKAGE = 'Rfast',x,ncores)
}

sort_mat_parallel <- function(x,ncores) {
  .Call('Rfast_sort_mat_p', PACKAGE = 'Rfast',x,ncores)
}

colMaxs_parallel <- function(x,ncores,value=FALSE) {
  .Call('Rfast_colmax_p', PACKAGE = 'Rfast',x,ncores,value)
}

colMins_parallel <- function(x,ncores,value=FALSE) {
  .Call('Rfast_colmin_p', PACKAGE = 'Rfast',x,ncores,value)
}