# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

floyd<-function(x){
  i4_huge<-2147483647
  y<-as.vector(x)
  y[is.na(y)]<-i4_huge
  dm<-ncol(x)
  y<-.Call('Rfast_floyd_john',dm,y)
  y[y==i4_huge]<-NA
  dim(y)<-c(dm,dm)
  y
}