# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g2Test <- function(data,x,y,cs,dc) {
    .Call('Rfast_g2Test', PACKAGE = 'Rfast',data,x,y,cs,dc)
}

g2Test_univariate_perm <- function(data,dc,nperm) {
    .Call('Rfast_g2Test_univariate_perm', PACKAGE = 'Rfast',data,dc,nperm)
}

g2Test_univariate <- function(data,dc) {
    .Call('Rfast_g2Test_univariate', PACKAGE = 'Rfast',data,dc)
}

g2Test_perm <- function(data,x,y,cs,dc,nperm) {
    .Call('Rfast_g2Test_perm', PACKAGE = 'Rfast',data,x,y,cs,dc,nperm)
}

