# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_element<-function(x,key){
  if(is.matrix(x))
    x<-as.vector(x)
  .Call('Rfast_is_element', x,key)
}