# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lower_tri <- function(x) {
	if(is.vector(x) && length(x)==2){
		return (.Call('Rfast_lower_tri_b', PACKAGE = 'Rfast',x[1L],x[2L]))
	}
	.Call('Rfast_lower_tri', PACKAGE = 'Rfast',x)
}