# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mahala <- function(x,mu,sigma,ncores = 1,ischol = FALSE) {
  if (!is.matrix(x)) 
    x <- matrix(x, 1, length(x))
  if (!is.matrix(sigma)) 
    sigma <- as.matrix(sigma)
  .Call('Rfast_mahaCpp', PACKAGE = 'Rfast',x,mu,sigma,ncores,ischol)
}