# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Match <- function(x,key) {
  if(is.null(key))
  	stop("Key cant be Null.")
  .Call('Rfast_Match',x,key)
}