# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permutation_prev <- function(x,all_prev=TRUE) {
  .Call('Rfast_permutation_prev',x,all_prev)
}