# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permutation_next <- function(x,all_next=TRUE) {
  .Call('Rfast_permutation_next',x,all_next)
}