# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_index <- function(x, descending = FALSE) {
  .Call('Rfast_sort_index',x,descending)
}