# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_unique <- function(x) {
  if(is.double(x)){
  	return (.Call('Rfast_sort_uniq_double',x))
  }
  .Call('Rfast_sort_uniq_int',x)
}