# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

upper_tri <- function(x,suma = FALSE) {
  	if(is.vector(x) && length(x)==2){
		.Call('Rfast_upper_tri_b', PACKAGE = 'Rfast',x[1L],x[2L])
	}else if(suma){
		.Call('Rfast_sum_upper_tri', PACKAGE = 'Rfast',x)	
	}else{
		.Call('Rfast_upper_tri', PACKAGE = 'Rfast',x)
	}
}